oscarotero/keep-a-changelog

src/Release.js
test/index.js

`Release.prototype.isEmpty` had inverted logic for checking whether changes exist.  This PR fixes that and adds some tests around the function

Fix Release isEmpty and add tests

---

src/Changelog.js
test/empty.expected.md
test/index.js

This PR fixes an issue where there are multiple consecutive trailing newlines for newly created 
Changelogs or Changelogs without links (or compare links).

Fix trailing newlines when no links are present

---

CHANGELOG.md
src/Release.js
test/changelog.expected.md

Following https://keepachangelog.com/en/1.0.0/ , the unreleased version should be titled `Unreleased` instead of `UNRELEASED`.  This PR changes the case of the title to reflect that.

Fix case of unreleased version title

---

CHANGELOG.md
example.js
src/Changelog.js
src/Release.js
test/index.js

This PR adds the following functions:
- `Changelog.prototype.findRelease` - finds a release by version number
- `Release.prototype.setVersion` - updates a release's version (and re-sorts the releases in the changelog)
Tests were added for `setVersion`, and I can add tests for `findRelease` as well if you want

Add functions for finding a release by version and for changing a release version

---

src/Change.js
test/Change.js

This PR updates the regular expressions used in `extractIssues` to narrow down issue extraction and prevent unwanted extraction of issues.  This has started to come up often in our use of keep-a-changelog around CSS color values which only involve numbers (i.e. #888888).  Issues are now extracted using stricter rules.
- Issues with brackets
- Always extracted unless the leading bracket is escaped or the brackets are already part of a link.
- Issues without brackets
- Must be preceded by whitespace or a comma (or be at the start of the line)
- Must be followed by whitespace, a comma, or a period (or be at the end of the line)
Also added a lot of test cases around issue extraction which should hopefully cover most possibilities.
Resolves https://github.com/brightcove/kacl/issues/11

Update issue regexes to prevent unwanted extractions

---

CHANGELOG.md
src/Release.js
test/index.js

Similar to setVersion, this PR adds a setDate function in order to allow setting the date of an existing release.
My use case scenario is that I have an [Unreleased] release which doesn't have a date, and I'd like to programmatically promote this Unreleased version into a proper version with semver and also with the date specified.

Added  setDate function to  for changing the date of a release.

---

CHANGELOG.md
README.md
package.json
src/parser.js
test/changelog.custom.type.md
test/fixture/CustomRelease.js
test/index.js
test/parser.js

- extend `Release` class
- test extended Release
- parser change + test parser with custom release
- update readme + changelog
I'm not sure who is actually using the code, but I tried avoiding new JS stuff, like arrow functions or object destructuring so it work with older versions of Node.

Ability to add new Change Types

---

src/parser.js
test/changelog.md
test/parser.js

Detect and handle cases where the URL for a reference link is on the line after its label. This situation is created by using Prettier to format a Changelog file.
Discussion: https://github.com/oscarotero/keep-a-changelog/issues/16

Issue #16: recognize and parse two-line reference links

---

bin.ts

The `--latest-release` arg was not functioning, due to mismatch of the arg as parsed and the argv property.
also added the release flag to the spec as it wasn't in there, but the code looking for it is.

Fixes for release args

---

README.md

It needs the release version number to be effective.

Update README.md for --release arg

---

bin.ts

If a repository was cloned by `git clone https://github.com/oscarotero/keep-a-changelog/` (note the trailing slash) the fetched remote url contains a trailing slash and leads to links with 2 slashes.

Sanitize result of GetRemoteUrl

---

bin.ts

Since May 24th, 2021 gitlab.com changed it's default branch name from `master` to `main`. This commit allows to respect this change in the changelog.

Add cli argument head

---

src/parser.ts

`GitLab` compare links contain a dash, the dash was not correctly removed from the base url and this leads to incremented dashes in the compare and tag links.
On the other hand we also could sanitize the links somewhere else.

Fix changelog parser for gitlab links

---

src/parser.ts
test/changelog.gitlab.md
test/parser.test.ts

The first group used a greedy match, so that it always matched the dash that gitlab uses in front of `compare`. The optional group was not enough to remove the dash from the matched link.
I am so sorry for the broken merge requests. I added a test to avoid further broken releases.

Fix regex for GitLab links in parser.ts

---

bin.ts

The original implementation did not handle https URLs. If one cloned a repository via https://github.com/my/project.git the URL in `CHANGELOG.md` still contained the .git suffix. This is only a issue if a new `CHANGELOG.md` file is created by `--init`, otherwise the correct URL is taken from existing tag / compare entries.
Also the remoteUrls protocol does not need to be set by hand, since new URL() seems to parse the correct protocol from the URL.
I tested the implementation with these inputs:
```
console.log(normalizeUrl("git@github.com:my/proj.git", true).href == "https://github.com/my/proj")
console.log(normalizeUrl("git@github.com:my/proj", true).href == "https://github.com/my/proj")
console.log(normalizeUrl("https://github.com/my/proj.git", true).href == …
```

Improve URL normalization in bin.ts

---

README.md
bin.ts
src/Change.ts
src/Changelog.ts
src/Release.ts
test/Change.test.ts

This adds support for customizing the bullet point character used in unordered lists.

Add bullet style support

---

src/Changelog.ts
src/parser.ts
src/settings.ts
test/changelog.azdo.md
test/parser.test.ts

Adds Azure DevOps URL format support.
I'm not particularly satisfied with the way I had to detect if `tag` match a branch or a tag. Azure DevOps needs to be told explicitly which it is (by using `GB` or `GT`, respectively) and what I've implemented will only work on the `unreleased` URL. I'm open to suggestions on how to handle this properly.

Add Azure DevOps URL support

---

bin.ts

This fixes the `--create` option creating a new Unreleased section even if it already exists in the changelog.
I'm not sure what are the contribution rules are for this repository so feel free to provide feedback if needed.

Skip release creation if it already exists

---

src/settings.ts

Hi there, 
I added BitBucket support to the tag / compare URL builder.
Thanks for your tool, it helps me a lot :)

Tag and Comparison URL - added support for BitBucket

---

src/parser.ts
test/changelog.bitbucket.md
test/parser.test.ts

Hey,
It's me again.
I found a bug in the parsing of BitBucket comparison URLs.
The comparison URLs of BitBucket follow this structure:
```
https://bitbucket.org/<org-name>/<repo-name>/branches/compare/<NewTag>%D0<OldTag>
```
The `/branches` part was not removed during URL parsing, leading to another `/branches` part being added every time the tool was run, like this:
```
https://bitbucket.org/<org-name>/<repo-name>/branches/compare/<NewTag>%D0<OldTag>
https://bitbucket.org/<org-name>/<repo-name>/branches/branches/compare/<NewTag>%D0<OldTag>
https://bitbucket.org/<org-name>/<repo-name>/branches/branches/branches/compare/<NewTag>%D0<OldTag>
...
```
This bugfix should fix this problem.
Thanks for taking a look!

Bugfix: BitBucket URLs improperly parsed
